#!/usr/bin/env bash
# scripts/make-report-index.sh
#
# Generates ./reports/index.html — a simple, professional landing page linking the
# test and coverage HTML reports (per CONTRIBUTING.md optional HTML index).
# Safe to run standalone; links are only shown for reports that exist.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPORTS="$REPO_ROOT/reports"
mkdir -p "$REPORTS"

test_link=""
if [[ -f "$REPORTS/testing/index.html" ]]; then
  test_link='<li><a href="testing/index.html">Test results</a> — pass/fail summary by suite (JUnit XML alongside at <code>testing/junit.xml</code>).</li>'
else
  test_link='<li>Test results — not generated yet. Run <code>make test</code>.</li>'
fi

cov_link=""
if [[ -f "$REPORTS/coverage/html/index.html" ]]; then
  cov_link='<li><a href="coverage/html/index.html">Code coverage</a> — line/region coverage by file (lcov data alongside at <code>coverage/coverage.lcov</code>).</li>'
else
  cov_link='<li>Code coverage — not generated yet. Run <code>make coverage</code>.</li>'
fi

cat > "$REPORTS/index.html" <<HTML
<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<title>rawm — Reports</title>
<style>
 body{font:15px -apple-system,system-ui,sans-serif;margin:2.5rem;color:#1f2328;max-width:720px}
 h1{font-size:1.5rem} ul{line-height:1.9} code{background:#f6f8fa;padding:.1rem .3rem;border-radius:4px}
 .note{color:#57606a;font-size:.9rem;margin-top:1.5rem}
</style></head><body>
<h1>rawm — Test &amp; Coverage Reports</h1>
<ul>
  $test_link
  $cov_link
</ul>
<p class="note">Generated by <code>make test</code> / <code>make coverage</code>. This
directory is gitignored. Coverage target: 90% incl. branches (Swift emits region
coverage as the branch-sensitive metric).</p>
</body></html>
HTML

echo "[reports] wrote $REPORTS/index.html"
